### ISSUE TITLE
How are you computing Color value to LinearRGB and SRGB?

### ISSUE THREAD

**Issue by surajsubudhi10** [BlauHimmel/Hikari#3]
If you can mention any reference for computing LinearRGB and SRGB will be great. Want to know what are those magic numbers.

https://github.com/BlauHimmel/Hikari/blob/fe237fa8e8aaab5da72201bc18b7fb8d539c894f/src/core/Color.cpp#L57-L93

**Comment by BlauHimmel** [comment]
Maybe these materials can help you:
1. <<Physically based rendering 3rd>> Page. 621
2.  https://en.wikipedia.org/wiki/SRGB  Sec. 3 Specification of the transformation
3.  https://www.w3.org/Graphics/Color/srgb
4.  http://www.ryanjuckett.com/programming/rgb-color-space-conversion/

**Comment by surajsubudhi10** [comment]
Thank you for the references.
